#!/usr/bin/env python3
"""
dunbar sync — keep your contacts.csv in sync with your circle folders, and
auto-regenerate the summary block at the top of each person's markdown file.

数据契约 (data contract):
  Filesystem is the source of truth for: which circle a person is in, and
    the path to their .md profile.
  contacts.csv is the source of truth for: every other column (phone, email,
    tags, birthday, ...).
  The block at the top of every person MD between
    <!-- CSV-SYNC-BEGIN ... -->
    <!-- CSV-SYNC-END -->
  is generated by this script. Don't hand-edit it. Edit the CSV instead.
  Everything outside that block (background, interactions, preferences, ...)
  is yours — sync.py never touches it.

Usage:
  ./sync.py                   # apply: write CSV + regenerate MD summary blocks
  ./sync.py --root path/to    # work in a different root (default: cwd)
  ./sync.py --dry-run         # preview only
  ./sync.py --no-md-sync      # only sync CSV, skip MD summary refresh
  ./sync.py --verbose

Detection:
  🔄 Moved    — a person changed circle           → patch CSV
  ✨ New      — folder exists but no CSV row      → append new row (stub fields)
  ⚠️  Orphan  — CSV row exists but folder missing → warning only (you decide)
  📝 MD-sync  — refresh the summary block at the top of each person's MD

Optional config:
  dunbar.config.json in the root lets you rename / re-order circles, e.g.:
    {
      "circles": {
        "01_inner": "inner",
        "02_close": "close",
        "03_warm":  "warm"
      }
    }
  Without a config file, the default 5 Dunbar circles are used
  (核心 / 挚友 / 常联系 / 熟人 / 弱联系).
"""

from __future__ import annotations

import argparse
import csv
import json
import re
import sys
from pathlib import Path

# Default circles — bilingual folder names + Chinese display labels.
# Override in dunbar.config.json if you want English labels, fewer circles, etc.
DEFAULT_CIRCLES = {
    "01_核心_core":      "核心",
    "02_挚友_inner":     "挚友",
    "03_常联系_regular": "常联系",
    "04_熟人_casual":    "熟人",
    "05_弱联系_weak":    "弱联系",
}

SYNC_BEGIN = "<!-- CSV-SYNC-BEGIN: auto-generated from contacts.csv by sync.py — do not edit -->"
SYNC_END   = "<!-- CSV-SYNC-END -->"

# Month abbrev → number, for un-mangling dates that Numbers/Excel localized
# (e.g. it'll silently turn "04-15" into "Apr-15")
_MONTH_ABBR = {
    "Jan": "01", "Feb": "02", "Mar": "03", "Apr": "04",
    "May": "05", "Jun": "06", "Jul": "07", "Aug": "08",
    "Sep": "09", "Oct": "10", "Nov": "11", "Dec": "12",
}


# ───────────────────────── config ─────────────────────────

def load_circles(root: Path) -> dict[str, str]:
    cfg = root / "dunbar.config.json"
    if not cfg.exists():
        return DEFAULT_CIRCLES
    try:
        data = json.loads(cfg.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        print(f"⚠️  dunbar.config.json is not valid JSON ({e}). Using defaults.", file=sys.stderr)
        return DEFAULT_CIRCLES
    circles = data.get("circles")
    if not isinstance(circles, dict) or not circles:
        return DEFAULT_CIRCLES
    return circles


# ───────────────────────── date normalization ─────────────────────────

def normalize_date(s: str, allow_md_only: bool = False) -> str:
    """Normalize date strings that Numbers/Excel may have mangled.
       DD/MM/YYYY -> YYYY-MM-DD
       Apr-15     -> 04-15   (birthday MM-DD)
       Already-ISO strings pass through.
    """
    s = (s or "").strip()
    if not s:
        return s
    if re.fullmatch(r"\d{4}-\d{2}-\d{2}", s):
        return s
    if allow_md_only and re.fullmatch(r"\d{2}-\d{2}", s):
        return s
    m = re.fullmatch(r"(\d{1,2})/(\d{1,2})/(\d{4})", s)
    if m:
        d, mo, y = m.groups()
        return f"{y}-{int(mo):02d}-{int(d):02d}"
    m = re.fullmatch(r"([A-Za-z]{3})[-\s](\d{1,2})", s)
    if m and m.group(1) in _MONTH_ABBR:
        mo = _MONTH_ABBR[m.group(1)]
        return f"{mo}-{int(m.group(2)):02d}"
    return s  # Leave alone — user may have written "today" or similar


def normalize_csv_dates(header: list[str], data: list[list[str]]) -> list[tuple[str, str, str, str]]:
    """Normalize known date columns. Returns [(nickname, column, old, new)]."""
    changes: list[tuple[str, str, str, str]] = []
    if "昵称" not in header:
        return changes
    nick_col = header.index("昵称")

    # 上次见面 (last_seen) → ISO YYYY-MM-DD; tolerate legacy "上次联系" column name
    last_col_name = "上次见面" if "上次见面" in header else ("上次联系" if "上次联系" in header else None)
    if last_col_name:
        col = header.index(last_col_name)
        for row in data:
            old = row[col]
            new = normalize_date(old)
            if new != old:
                changes.append((row[nick_col], last_col_name, old, new))
                row[col] = new

    # 生日 → MM-DD or YYYY-MM-DD
    if "生日" in header:
        col = header.index("生日")
        for row in data:
            old = row[col]
            new = normalize_date(old, allow_md_only=True)
            if new != old:
                changes.append((row[nick_col], "生日", old, new))
                row[col] = new

    return changes


# ───────────────────────── scan ─────────────────────────

def scan_fs(root: Path, circles: dict[str, str]) -> dict[str, tuple[str, str]]:
    """Walk circle directories and collect (nickname → (circle_label, md_relpath))."""
    state: dict[str, tuple[str, str]] = {}
    for folder_name, circle in circles.items():
        circle_dir = root / folder_name
        if not circle_dir.exists():
            continue
        for person_dir in sorted(circle_dir.iterdir()):
            if not person_dir.is_dir():
                continue
            nickname = person_dir.name
            preferred = person_dir / f"{nickname}.md"
            if preferred.exists():
                md_name = preferred.name
            else:
                mds = sorted(person_dir.glob("*.md"))
                md_name = mds[0].name if mds else ""
            detail = f"{folder_name}/{nickname}/{md_name}" if md_name else ""
            state[nickname] = (circle, detail)
    return state


def read_csv(csv_path: Path) -> tuple[list[str], list[list[str]]]:
    with csv_path.open(newline="", encoding="utf-8") as f:
        rows = list(csv.reader(f))
    return rows[0], rows[1:]


def write_csv(csv_path: Path, header: list[str], data: list[list[str]]) -> None:
    with csv_path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(header)
        writer.writerows(data)


# ───────────────────────── MD summary block ─────────────────────────

def build_summary(row: list[str], header: list[str]) -> str:
    """Build a one-line markdown blockquote summary from a CSV row."""
    def get(col: str) -> str:
        try:
            return row[header.index(col)]
        except (ValueError, IndexError):
            return ""

    parts: list[str] = []

    # Relationship cadence: circle + last seen
    trio: list[str] = []
    if get("圈层"):
        trio.append(f"**{get('圈层')}**")
    last_seen = get("上次见面") or get("上次联系")  # legacy fallback
    if last_seen:
        trio.append(f"上次见 {last_seen}")
    if trio:
        parts.append(" · ".join(trio))

    # Identity
    iden: list[str] = []
    nick = get("昵称")
    real = get("真实姓名")
    if real and real != nick:
        iden.append(real)
    if get("身份"):
        iden.append(get("身份"))
    company, title = get("公司"), get("职位")
    if company and title:
        iden.append(f"{company} {title}")
    elif company:
        iden.append(company)
    elif title:
        iden.append(title)
    if iden:
        parts.append(" · ".join(iden))

    # One contact channel (Email > Phone > WeChat)
    contact = get("Email") or get("电话") or get("微信")
    if contact:
        parts.append(contact)

    # Addresses (home / office — useful for tap-to-navigate on mobile)
    addrs: list[str] = []
    home = get("家庭地址")
    office = get("办公地址")
    if home:
        addrs.append(f"🏠 {home}")
    if office:
        addrs.append(f"🏢 {office}")
    if addrs:
        parts.append(" · ".join(addrs))

    if get("标签"):
        parts.append(f"标签: {get('标签')}")

    return "> " + " · ".join(parts) if parts else "> *no CSV summary yet*"


# Strip any legacy YAML frontmatter at the very top of the file (one-time cleanup).
_YAML_FM = re.compile(r"\A---\n.*?\n---\n+", re.DOTALL)
# Existing sync block.
_SYNC_BLOCK = re.compile(
    re.escape(SYNC_BEGIN) + r".*?" + re.escape(SYNC_END) + r"\n*",
    re.DOTALL,
)
# Tolerate the older Chinese-language begin marker so re-runs don't double-stack.
_LEGACY_SYNC_BLOCK = re.compile(
    r"<!--\s*CSV-SYNC-BEGIN[^>]*-->.*?<!--\s*CSV-SYNC-END\s*-->\n*",
    re.DOTALL,
)


def regen_md_summary(md_path: Path, row: list[str], header: list[str]) -> str | None:
    """Rewrite the sync block at the top of an MD file.
       Returns 'updated' / 'created' / 'noop' / None (file missing)."""
    if not md_path.exists():
        return None
    original = md_path.read_text(encoding="utf-8")
    text = original

    text = _YAML_FM.sub("", text, count=1)

    new_block = f"{SYNC_BEGIN}\n{build_summary(row, header)}\n{SYNC_END}"

    if _SYNC_BLOCK.search(text):
        new_text = _SYNC_BLOCK.sub(new_block + "\n\n", text, count=1)
        outcome = "updated"
    elif _LEGACY_SYNC_BLOCK.search(text):
        new_text = _LEGACY_SYNC_BLOCK.sub(new_block + "\n\n", text, count=1)
        outcome = "updated"
    else:
        new_text = new_block + "\n\n" + text
        outcome = "created"

    if new_text == original:
        return "noop"
    md_path.write_text(new_text, encoding="utf-8")
    return outcome


# ───────────────────────── main ─────────────────────────

def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--root",
        default=".",
        help="path to your dunbar root (where contacts.csv + circle folders live). Default: cwd",
    )
    parser.add_argument("--dry-run", action="store_true", help="preview only, don't write")
    parser.add_argument("--verbose", "-v", action="store_true")
    parser.add_argument(
        "--no-md-sync",
        action="store_true",
        help="sync CSV only; skip refreshing the MD summary blocks",
    )
    args = parser.parse_args()

    root = Path(args.root).expanduser().resolve()
    csv_path = root / "contacts.csv"
    circles = load_circles(root)

    if not csv_path.exists():
        print(f"❌ contacts.csv not found in: {root}", file=sys.stderr)
        print(f"   (looking for {csv_path})", file=sys.stderr)
        return 1

    fs_state = scan_fs(root, circles)
    header, data = read_csv(csv_path)

    # Defensive: undo Numbers/Excel date mangling
    date_changes = normalize_csv_dates(header, data)

    try:
        nick_col = header.index("昵称")
        circle_col = header.index("圈层")
        detail_col = header.index("详档")
    except ValueError as e:
        print(f"❌ CSV header missing required column: {e}", file=sys.stderr)
        print(f"   (need 昵称, 圈层, 详档)", file=sys.stderr)
        return 1

    csv_index = {row[nick_col]: i for i, row in enumerate(data)}

    moves: list[tuple[str, str, str, str, str]] = []
    new_in_fs: list[tuple[str, str, str]] = []
    orphans: list[tuple[str, str, str]] = []

    # FS → CSV reconciliation
    for nickname, (circle, detail) in fs_state.items():
        if nickname not in csv_index:
            new_in_fs.append((nickname, circle, detail))
            continue
        i = csv_index[nickname]
        old_circle = data[i][circle_col]
        old_detail = data[i][detail_col]
        if old_circle != circle or old_detail != detail:
            moves.append((nickname, old_circle, circle, old_detail, detail))
            if not args.dry_run:
                data[i][circle_col] = circle
                data[i][detail_col] = detail

    # Orphans (CSV has row, FS has no folder)
    for nickname, i in csv_index.items():
        if nickname not in fs_state:
            row = data[i]
            if row[circle_col] or row[detail_col]:
                orphans.append((nickname, row[circle_col], row[detail_col]))

    # Append rows for new FS-only people
    if not args.dry_run:
        for nickname, circle, detail in new_in_fs:
            row = [""] * len(header)
            row[nick_col] = nickname
            row[circle_col] = circle
            row[detail_col] = detail
            data.append(row)
        # rebuild index so MD sync can find new rows
        csv_index = {r[nick_col]: i for i, r in enumerate(data)}

    # ─── report (CSV side) ───
    n_circles = sum(1 for f in circles if (root / f).exists())
    print(f"📂 FS:  {len(fs_state)} people across {n_circles} circles")
    print(f"📋 CSV: {len(csv_index)} rows")
    print()

    if moves:
        print(f"🔄 Updates ({len(moves)}):")
        for nick, oc, nc, od, nd in moves:
            bits = []
            if oc != nc:
                bits.append(f"circle {oc or '∅'} → {nc}")
            if od != nd:
                bits.append(f"profile → {nd}")
            print(f"  • {nick}: {' / '.join(bits)}")
    if new_in_fs:
        verb = "will append" if args.dry_run else "appended"
        print(f"\n✨ New ({verb} {len(new_in_fs)} row{'s' if len(new_in_fs) != 1 else ''}):")
        for nick, circle, detail in new_in_fs:
            print(f"  + {nick} ({circle}) → {detail}")
        print("  ↳ only nickname/circle/profile filled — other columns left empty for you")
    if orphans:
        print(f"\n⚠️  Orphans ({len(orphans)}): CSV has row, FS has no folder")
        for nick, circle, detail in orphans:
            print(f"  ? {nick} (CSV: {circle}, {detail})")
        print("  ↳ not auto-deleted. If retired, remove the CSV row manually.")

    if date_changes:
        print(f"\n🗓️  Date normalized ({len(date_changes)}) (un-mangled from Numbers/Excel):")
        for nick, col, old, new in date_changes:
            print(f"  • {nick}.{col}: {old} → {new}")

    # Lint: 真实姓名 == 昵称 → suggest blanking 真实姓名 (means you only know the nickname)
    if "真实姓名" in header:
        real_col = header.index("真实姓名")
        same = [r[nick_col] for r in data if r[nick_col] and r[nick_col] == r[real_col]]
        if same:
            print(f"\n⚠️  Lint: 真实姓名 == 昵称 for: {', '.join(same)}")
            print("    (blank 真实姓名 until you know the full name)")

    # ─── write CSV ───
    if not args.dry_run and (moves or new_in_fs or date_changes):
        write_csv(csv_path, header, data)
        print(f"\n💾 CSV written: {csv_path.name}")

    # ─── refresh MD summary blocks ───
    if args.no_md_sync:
        print("\n(--no-md-sync — skipped MD summary refresh)")
    elif args.dry_run:
        print("\n(--dry-run — skipped MD summary refresh)")
    else:
        md_results = {"updated": [], "created": [], "noop": [], "missing": []}
        for nickname, (circle, detail) in fs_state.items():
            if nickname not in csv_index:
                continue
            row = data[csv_index[nickname]]
            md_path = root / detail if detail else None
            if md_path is None or not md_path.exists():
                md_results["missing"].append(nickname)
                continue
            outcome = regen_md_summary(md_path, row, header)
            if outcome:
                md_results[outcome].append(nickname)

        print()
        print("📝 MD summary sync:")
        if md_results["created"]:
            print(f"  ✨ first-time write: {', '.join(md_results['created'])}")
        if md_results["updated"]:
            print(f"  🔁 rewrote block:    {', '.join(md_results['updated'])}")
        if md_results["noop"] and args.verbose:
            print(f"  ✓  unchanged:        {', '.join(md_results['noop'])}")
        if md_results["missing"]:
            print(f"  ⚠️  missing MD file:  {', '.join(md_results['missing'])}")

    if not (moves or new_in_fs or orphans):
        print("\n✅ CSV / FS fully in sync.")

    if args.dry_run and (moves or new_in_fs):
        print("\n(--dry-run — nothing written. Drop --dry-run to apply.)")

    return 0


if __name__ == "__main__":
    sys.exit(main())
