#!/usr/bin/env python3
"""
dunbar sync — keep your CSV in sync with your circle folders, and auto-regenerate
the summary block at the top of each record's markdown profile.

Data contract:
  The filesystem is the source of truth for: which circle a record is in, and the
    path to its .md profile.
  The CSV is the source of truth for: every other column (phone, email, ABN,
    tags, dates, ...).
  The block at the top of every profile between
    <!-- CSV-SYNC-BEGIN ... -->
    <!-- CSV-SYNC-END -->
  is generated by this script. Don't hand-edit it. Edit the CSV instead.
  Everything outside that block (background, history, notes, ...) is yours —
  sync.py never touches it.

Usage:
  python sync.py                   # apply: write CSV + regenerate summary blocks
  python sync.py --root path/to    # work in a different root (default: cwd)
  python sync.py --dry-run         # preview only
  python sync.py --no-md-sync      # only sync the CSV, skip the summary refresh
  python sync.py --verbose

Detection:
  Moved    — a record changed circle           -> patch CSV
  New      — folder exists but no CSV row      -> append new row (stub fields)
  Orphan   — CSV row exists but folder missing -> warning only (you decide)
  MD-sync  — refresh the summary block at the top of each profile

Configuration:
  Everything below is overridable from `dunbar.config.json` in the root —
  circle folder names, CSV column names, which columns hold dates, and the shape
  of the generated summary line. With no config file, the defaults are the
  original 5 Dunbar circles with Chinese column names. See docs/schema.md.
"""

from __future__ import annotations

import argparse
import csv
import json
import re
import sys
from pathlib import Path

# Windows consoles default to a legacy code page and blow up on non-ASCII
# output. Force UTF-8 and never let a print() kill a sync run.
for _stream in (sys.stdout, sys.stderr):
    try:
        _stream.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass


# ───────────────────────── defaults ─────────────────────────

# Circle folders -> the label written into the circle column.
DEFAULT_CIRCLES = {
    "01_核心_core":      "核心",
    "02_挚友_inner":     "挚友",
    "03_常联系_regular": "常联系",
    "04_熟人_casual":    "熟人",
    "05_弱联系_weak":    "弱联系",
}

# The three structural columns the script cannot work without.
DEFAULT_COLUMNS = {
    "nickname": "昵称",   # unique key; must equal the folder name
    "circle":   "圈层",   # derived from the folder location
    "profile":  "详档",   # derived path to the .md file
}

# column name -> "full" (YYYY-MM-DD) | "monthday" (also allows MM-DD)
DEFAULT_DATES = {
    "上次见面": "full",
    "上次联系": "full",
    "生日":     "monthday",
}

# What a circle is called in the console output — "circle", "tier", "group"…
DEFAULT_NOUN = "circle"

# Warn when this column just repeats the nickname.
DEFAULT_LINT_DUPLICATE = "真实姓名"

# The generated summary line, left to right. Empty values are skipped.
#   {"col": ...}            one column
#   {"col": ..., "fallback": [...]}  first non-empty of col + fallbacks
#   {"any": [...]}          first non-empty of a list (e.g. Email > phone)
#   {"join": [...]}         space-joined (e.g. company + title)
#   "label"                 text prefix   |  "bold": true  -> **wrapped**
#   "skip_if_equals": "nickname"          -> drop when it duplicates the key
DEFAULT_SUMMARY = [
    {"col": "圈层", "bold": True},
    {"col": "上次见面", "fallback": ["上次联系"], "label": "上次见 "},
    {"col": "真实姓名", "skip_if_equals": "nickname"},
    {"col": "身份"},
    {"join": ["公司", "职位"]},
    {"any": ["Email", "电话", "微信"]},
    {"col": "家庭地址", "label": "🏠 "},
    {"col": "办公地址", "label": "🏢 "},
    {"col": "标签", "label": "标签: "},
]

SYNC_END = "<!-- CSV-SYNC-END -->"


def sync_begin(csv_name: str) -> str:
    return f"<!-- CSV-SYNC-BEGIN: auto-generated from {csv_name} by sync.py — do not edit -->"

# Month abbrev -> number, for un-mangling dates that Excel/Numbers localized
# (e.g. it will silently turn "04-15" into "Apr-15")
_MONTH_ABBR = {
    "Jan": "01", "Feb": "02", "Mar": "03", "Apr": "04",
    "May": "05", "Jun": "06", "Jul": "07", "Aug": "08",
    "Sep": "09", "Oct": "10", "Nov": "11", "Dec": "12",
}


class Config:
    """Resolved configuration for one dunbar root."""

    def __init__(self, data: dict | None = None):
        data = data or {}
        circles = data.get("circles")
        self.circles: dict[str, str] = (
            circles if isinstance(circles, dict) and circles else DEFAULT_CIRCLES
        )

        cols = data.get("columns")
        self.columns = dict(DEFAULT_COLUMNS)
        if isinstance(cols, dict):
            for key in DEFAULT_COLUMNS:
                if isinstance(cols.get(key), str) and cols[key].strip():
                    self.columns[key] = cols[key].strip()

        dates = data.get("dates")
        self.dates: dict[str, str] = (
            dates if isinstance(dates, dict) else DEFAULT_DATES
        )

        # An explicit null/"" disables the lint.
        if "lint_duplicate_of_nickname" in data:
            self.lint_duplicate = data["lint_duplicate_of_nickname"] or ""
        else:
            self.lint_duplicate = DEFAULT_LINT_DUPLICATE

        summary = data.get("summary")
        self.summary: list = summary if isinstance(summary, list) and summary else DEFAULT_SUMMARY

        noun = data.get("noun")
        self.noun: str = noun.strip() if isinstance(noun, str) and noun.strip() else DEFAULT_NOUN

        # The CSV filename itself is configurable — an accounting practice wants
        # clients.csv, not contacts.csv.
        name = data.get("csv")
        self.csv_name: str = name.strip() if isinstance(name, str) and name.strip() else "contacts.csv"

    @property
    def nickname_col(self) -> str:
        return self.columns["nickname"]

    @property
    def circle_col(self) -> str:
        return self.columns["circle"]

    @property
    def profile_col(self) -> str:
        return self.columns["profile"]


def load_config(root: Path) -> Config:
    cfg = root / "dunbar.config.json"
    if not cfg.exists():
        return Config()
    try:
        data = json.loads(cfg.read_text(encoding="utf-8-sig"))
    except json.JSONDecodeError as e:
        print(f"⚠️  dunbar.config.json is not valid JSON ({e}). Using defaults.", file=sys.stderr)
        return Config()
    if not isinstance(data, dict):
        print("⚠️  dunbar.config.json must be a JSON object. Using defaults.", file=sys.stderr)
        return Config()
    return Config(data)


# ───────────────────────── date normalization ─────────────────────────

def normalize_date(s: str, allow_md_only: bool = False) -> str:
    """Normalize date strings that Excel/Numbers may have mangled.
       DD/MM/YYYY -> YYYY-MM-DD
       Apr-15     -> 04-15   (month-day only)
       Already-ISO strings pass through.
    """
    s = (s or "").strip()
    if not s:
        return s
    if re.fullmatch(r"\d{4}-\d{2}-\d{2}", s):
        return s
    if allow_md_only and re.fullmatch(r"\d{2}-\d{2}", s):
        return s
    m = re.fullmatch(r"(\d{1,2})/(\d{1,2})/(\d{4})", s)
    if m:
        d, mo, y = m.groups()
        return f"{y}-{int(mo):02d}-{int(d):02d}"
    m = re.fullmatch(r"([A-Za-z]{3})[-\s](\d{1,2})", s)
    if m and m.group(1) in _MONTH_ABBR:
        mo = _MONTH_ABBR[m.group(1)]
        return f"{mo}-{int(m.group(2)):02d}"
    return s  # Leave alone — the user may have written "TBC" or similar


def normalize_csv_dates(header: list[str], data: list[list[str]], cfg: Config) -> list[tuple[str, str, str, str]]:
    """Normalize the configured date columns. Returns [(key, column, old, new)]."""
    changes: list[tuple[str, str, str, str]] = []
    if cfg.nickname_col not in header:
        return changes
    nick_col = header.index(cfg.nickname_col)

    for col_name, mode in cfg.dates.items():
        if col_name not in header:
            continue
        col = header.index(col_name)
        allow_md = str(mode).lower() in ("monthday", "md", "mm-dd")
        for row in data:
            if col >= len(row):
                continue
            old = row[col]
            new = normalize_date(old, allow_md_only=allow_md)
            if new != old:
                changes.append((row[nick_col], col_name, old, new))
                row[col] = new

    return changes


# ───────────────────────── scan ─────────────────────────

def scan_fs(root: Path, circles: dict[str, str]) -> dict[str, tuple[str, str]]:
    """Walk circle directories and collect (key -> (circle_label, md_relpath))."""
    state: dict[str, tuple[str, str]] = {}
    for folder_name, circle in circles.items():
        circle_dir = root / folder_name
        if not circle_dir.exists():
            continue
        for person_dir in sorted(circle_dir.iterdir()):
            if not person_dir.is_dir():
                continue
            nickname = person_dir.name
            preferred = person_dir / f"{nickname}.md"
            if preferred.exists():
                md_name = preferred.name
            else:
                mds = sorted(person_dir.glob("*.md"))
                md_name = mds[0].name if mds else ""
            detail = f"{folder_name}/{nickname}/{md_name}" if md_name else ""
            state[nickname] = (circle, detail)
    return state


def read_csv(csv_path: Path) -> tuple[list[str], list[list[str]], str]:
    """Read the CSV. Returns (header, rows, encoding-to-write-back-with).

    Excel on Windows saves CSVs with a UTF-8 BOM; utf-8-sig strips it on read
    so column lookups still work, and we write back in whatever the file used.
    """
    raw = csv_path.read_bytes()
    encoding = "utf-8-sig" if raw.startswith(b"\xef\xbb\xbf") else "utf-8"
    with csv_path.open(newline="", encoding="utf-8-sig") as f:
        rows = list(csv.reader(f))
    if not rows:
        return [], [], encoding
    return rows[0], rows[1:], encoding


def write_csv(csv_path: Path, header: list[str], data: list[list[str]], encoding: str = "utf-8") -> None:
    with csv_path.open("w", newline="", encoding=encoding) as f:
        writer = csv.writer(f)
        writer.writerow(header)
        writer.writerows(data)


# ───────────────────────── MD summary block ─────────────────────────

def build_summary(row: list[str], header: list[str], cfg: Config) -> str:
    """Build a one-line markdown blockquote summary from a CSV row."""
    def get(col: str) -> str:
        try:
            return row[header.index(col)].strip()
        except (ValueError, IndexError, AttributeError):
            return ""

    nickname = get(cfg.nickname_col)
    parts: list[str] = []

    for entry in cfg.summary:
        if not isinstance(entry, dict):
            continue

        if "any" in entry:
            value = next((get(c) for c in entry["any"] if get(c)), "")
        elif "join" in entry:
            value = " ".join(v for v in (get(c) for c in entry["join"]) if v)
        else:
            value = get(entry.get("col", ""))
            for fb in entry.get("fallback", []):
                if not value:
                    value = get(fb)

        if not value:
            continue
        if entry.get("skip_if_equals") == "nickname" and value == nickname:
            continue
        if entry.get("bold"):
            value = f"**{value}**"
        parts.append(f"{entry.get('label', '')}{value}")

    return "> " + " · ".join(parts) if parts else "> *no CSV summary yet*"


# Strip any legacy YAML frontmatter at the very top of the file (one-time cleanup).
_YAML_FM = re.compile(r"\A---\n.*?\n---\n+", re.DOTALL)
# Any sync block, current or legacy — so re-runs never double-stack.
_SYNC_BLOCK = re.compile(
    r"<!--\s*CSV-SYNC-BEGIN[^>]*-->.*?<!--\s*CSV-SYNC-END\s*-->\n*",
    re.DOTALL,
)


def regen_md_summary(md_path: Path, row: list[str], header: list[str], cfg: Config) -> str | None:
    """Rewrite the sync block at the top of a profile.
       Returns 'updated' / 'created' / 'noop' / None (file missing)."""
    if not md_path.exists():
        return None
    original = md_path.read_text(encoding="utf-8")
    text = _YAML_FM.sub("", original, count=1)

    new_block = f"{sync_begin(cfg.csv_name)}\n{build_summary(row, header, cfg)}\n{SYNC_END}"

    if _SYNC_BLOCK.search(text):
        new_text = _SYNC_BLOCK.sub(lambda _: new_block + "\n\n", text, count=1)
        outcome = "updated"
    else:
        new_text = new_block + "\n\n" + text
        outcome = "created"

    if new_text == original:
        return "noop"
    md_path.write_text(new_text, encoding="utf-8")
    return outcome


# ───────────────────────── main ─────────────────────────

def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--root",
        default=".",
        help="path to your dunbar root (where the CSV + circle folders live). Default: cwd",
    )
    parser.add_argument("--dry-run", action="store_true", help="preview only, don't write")
    parser.add_argument("--verbose", "-v", action="store_true")
    parser.add_argument(
        "--no-md-sync",
        action="store_true",
        help="sync the CSV only; skip refreshing the summary blocks",
    )
    args = parser.parse_args()

    root = Path(args.root).expanduser().resolve()
    cfg = load_config(root)
    csv_path = root / cfg.csv_name

    if not csv_path.exists():
        print(f"❌ {cfg.csv_name} not found in: {root}", file=sys.stderr)
        print(f"   (looking for {csv_path})", file=sys.stderr)
        return 1

    fs_state = scan_fs(root, cfg.circles)
    header, data, encoding = read_csv(csv_path)

    # Defensive: undo Excel/Numbers date mangling
    date_changes = normalize_csv_dates(header, data, cfg)

    try:
        nick_col = header.index(cfg.nickname_col)
        circle_col = header.index(cfg.circle_col)
        detail_col = header.index(cfg.profile_col)
    except ValueError as e:
        print(f"❌ CSV header missing required column: {e}", file=sys.stderr)
        print(f"   (need {cfg.nickname_col}, {cfg.circle_col}, {cfg.profile_col})", file=sys.stderr)
        return 1

    # Rows shorter than the header (hand-edited CSVs do this) would crash on
    # index assignment — pad them up front.
    for row in data:
        if len(row) < len(header):
            row.extend([""] * (len(header) - len(row)))

    csv_index = {row[nick_col]: i for i, row in enumerate(data) if row[nick_col]}

    moves: list[tuple[str, str, str, str, str]] = []
    new_in_fs: list[tuple[str, str, str]] = []
    orphans: list[tuple[str, str, str]] = []

    # FS -> CSV reconciliation
    for nickname, (circle, detail) in fs_state.items():
        if nickname not in csv_index:
            new_in_fs.append((nickname, circle, detail))
            continue
        i = csv_index[nickname]
        old_circle = data[i][circle_col]
        old_detail = data[i][detail_col]
        if old_circle != circle or old_detail != detail:
            moves.append((nickname, old_circle, circle, old_detail, detail))
            if not args.dry_run:
                data[i][circle_col] = circle
                data[i][detail_col] = detail

    # CSV rows with no folder. Two different situations:
    #   orphan   — it used to have one (tier/profile still filled) -> something got deleted
    #   unfiled  — it never had one (tier/profile blank) -> typed into the spreadsheet first
    unfiled: list[str] = []
    for nickname, i in csv_index.items():
        if nickname not in fs_state:
            row = data[i]
            if row[circle_col] or row[detail_col]:
                orphans.append((nickname, row[circle_col], row[detail_col]))
            else:
                unfiled.append(nickname)

    # Append rows for folders that have no CSV row yet
    if not args.dry_run:
        for nickname, circle, detail in new_in_fs:
            row = [""] * len(header)
            row[nick_col] = nickname
            row[circle_col] = circle
            row[detail_col] = detail
            data.append(row)
        # rebuild the index so the MD sync below can find the new rows
        csv_index = {r[nick_col]: i for i, r in enumerate(data) if r[nick_col]}

    # ─── report (CSV side) ───
    n_circles = sum(1 for f in cfg.circles if (root / f).exists())
    print(f"📂 Folders: {len(fs_state)} records across {n_circles} {cfg.noun}s")
    print(f"📋 CSV:     {len(csv_index)} rows")
    print()

    if moves:
        print(f"🔄 Updates ({len(moves)}):")
        for nick, oc, nc, od, nd in moves:
            bits = []
            if oc != nc:
                bits.append(f"{cfg.noun} {oc or '∅'} → {nc}")
            if od != nd:
                bits.append(f"profile → {nd}")
            print(f"  • {nick}: {' / '.join(bits)}")
    if new_in_fs:
        verb = "will append" if args.dry_run else "appended"
        print(f"\n✨ New ({verb} {len(new_in_fs)} row{'s' if len(new_in_fs) != 1 else ''}):")
        for nick, circle, detail in new_in_fs:
            print(f"  + {nick} ({circle}) → {detail}")
        print(f"  ↳ only key/{cfg.noun}/profile filled — other columns left empty for you")
    if orphans:
        print(f"\n⚠️  Orphans ({len(orphans)}): the CSV has a row, the filesystem has no folder")
        for nick, circle, detail in orphans:
            print(f"  ? {nick} (CSV: {circle}, {detail})")
        print("  ↳ not auto-deleted. If retired, remove the CSV row manually.")
    if unfiled:
        print(f"\n⏳ Not filed yet ({len(unfiled)}): a CSV row with no folder")
        for nick in unfiled:
            print(f"  · {nick}")
        print("  ↳ create <tier>/<name>/<name>.md and re-run, and the row gets picked up.")

    if date_changes:
        print(f"\n🗓️  Dates normalized ({len(date_changes)}) (un-mangled from Excel/Numbers):")
        for nick, col, old, new in date_changes:
            print(f"  • {nick}.{col}: {old} → {new}")

    # Lint: a column that just repeats the nickname carries no information
    if cfg.lint_duplicate and cfg.lint_duplicate in header:
        dup_col = header.index(cfg.lint_duplicate)
        same = [r[nick_col] for r in data if r[nick_col] and r[nick_col] == r[dup_col]]
        if same:
            print(f"\n⚠️  Lint: {cfg.lint_duplicate} == {cfg.nickname_col} for: {', '.join(same)}")
            print(f"    (blank {cfg.lint_duplicate} until you know the real one)")

    # ─── write CSV ───
    if not args.dry_run and (moves or new_in_fs or date_changes):
        write_csv(csv_path, header, data, encoding)
        print(f"\n💾 CSV written: {csv_path.name}")

    # ─── refresh MD summary blocks ───
    if args.no_md_sync:
        print("\n(--no-md-sync — skipped the summary refresh)")
    elif args.dry_run:
        print("\n(--dry-run — skipped the summary refresh)")
    else:
        md_results: dict[str, list[str]] = {"updated": [], "created": [], "noop": [], "missing": []}
        for nickname, (circle, detail) in fs_state.items():
            if nickname not in csv_index:
                continue
            row = data[csv_index[nickname]]
            md_path = root / detail if detail else None
            if md_path is None or not md_path.exists():
                md_results["missing"].append(nickname)
                continue
            outcome = regen_md_summary(md_path, row, header, cfg)
            if outcome:
                md_results[outcome].append(nickname)

        print()
        print("📝 Profile summary sync:")
        if md_results["created"]:
            print(f"  ✨ first-time write: {', '.join(md_results['created'])}")
        if md_results["updated"]:
            print(f"  🔁 rewrote block:    {', '.join(md_results['updated'])}")
        if md_results["noop"] and args.verbose:
            print(f"  ✓  unchanged:        {', '.join(md_results['noop'])}")
        if md_results["missing"]:
            print(f"  ⚠️  missing profile:  {', '.join(md_results['missing'])}")

    if not (moves or new_in_fs or orphans or unfiled):
        print("\n✅ CSV / folders fully in sync.")

    if args.dry_run and (moves or new_in_fs):
        print("\n(--dry-run — nothing written. Drop --dry-run to apply.)")

    return 0


if __name__ == "__main__":
    sys.exit(main())
